export const categories = [
  {
    id: 1,
    name: "Sweets",
    image: require("../assets/images/bikeGuy.jpg"),
  },
  {
    id: 2,
    name: "Sweets",
    image: require("../assets/images/bikeGuy.jpg"),
  },
  {
    id: 3,
    name: "Sweets",
    image: require("../assets/images/bikeGuy.jpg"),
  },
  {
    id: 4,
    name: "Sweets",
    image: require("../assets/images/bikeGuy.jpg"),
  },
  {
    id: 5,
    name: "Sweets",
    image: require("../assets/images/bikeGuy.jpg"),
  },
  {
    id: 6,
    name: "Sweets",
    image: require("../assets/images/bikeGuy.jpg"),
  },
  {
    id: 7,
    name: "Sweets",
    image: require("../assets/images/bikeGuy.jpg"),
  },
  {
    id: 8,
    name: "Sweets",
    image: require("../assets/images/bikeGuy.jpg"),
  },
];

export const featured = {
  id: 1,
  title: "Hot and Spicy",
  description: "soft and tender fried chicken",
  restaurants: [
    {
      id: 1,
      name: "Papa Johns",
      image: require("../assets/images/bikeGuy.jpg"),
      description: "Hot and spicy chicken",
      lng: 38.2145602,
      lat: -85.5324269,
      address: "434 second street",
      stars: 4,
      reviews: "4.5k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 20,
          image: require("../assets/images/bikeGuy.jpg"),
        },
        {
          id: 2,
          name: "Burger",
          description: "cheezy garlic pizza",
          price: 20,
          image: require("../assets/images/bikeGuy.jpg"),
        },
        {
          id: 3,
          name: "Coffee",
          description: "cheezy garlic pizza",
          price: 20,
          image: require("../assets/images/bikeGuy.jpg"),
        },
      ],
    },
    {
      id: 2,
      name: "Johny Smith",
      image: require("../assets/images/bikeGuy.jpg"),
      description: "Hot and spicy chicken",
      lng: 38.2145602,
      lat: -85.5324269,
      address: "434 second street",
      stars: 4,
      reviews: "4.5k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 20,
          image: require("../assets/images/bikeGuy.jpg"),
        },
        {
          id: 2,
          name: "Burger",
          description: "cheezy garlic pizza",
          price: 20,
          image: require("../assets/images/bikeGuy.jpg"),
        },
        {
          id: 3,
          name: "Coffee",
          description: "cheezy garlic pizza",
          price: 20,
          image: require("../assets/images/bikeGuy.jpg"),
        },
      ],
    },
    {
      id: 3,
      name: "Pops Carls",
      image: require("../assets/images/bikeGuy.jpg"),
      description: "Hot and spicy chicken",
      lng: 38.2145602,
      lat: -85.5324269,
      address: "434 second street",
      stars: 4,
      reviews: "4.5k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 20,
          image: require("../assets/images/bikeGuy.jpg"),
        },
        {
          id: 2,
          name: "Burger",
          description: "cheezy garlic pizza",
          price: 20,
          image: require("../assets/images/bikeGuy.jpg"),
        },
        {
          id: 3,
          name: "Coffee",
          description: "cheezy garlic pizza",
          price: 20,
          image: require("../assets/images/bikeGuy.jpg"),
        },
      ],
    },
  ],
};
